sudo: require
services:
    - docker

before_install:
    - docker build -t jahangirdevs/docker-react -f Dockerfile.dev .

script:
    - docker run jahangirdevs/docker-react npm run test -- --coverage
